### ISSUE TITLE
docker instructions issues on Ubuntu 16.04

### ISSUE THREAD

**Issue by asah** [src-d/ast2vec#99]
(Ubuntu 16.04)

$ docker build -t srcd/ast2vec .
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
$ sudo docker build -t srcd/ast2vec .
Sending build context to Docker daemon 59.96 MB
...
==> appears to need to run as root?  

docker run -d --privileged -p 9432:9432 --name bblfsh --rm bblfsh/server
==> Conflicting options: --rm and -d
==> https://github.com/moby/moby/issues/27812
==> need docker 1.13 or later  (Ubuntu 16.04 defaults to 1.12.6, build 78d1802)

**Comment by vmarkovtsev** [comment]
Almost there! I updated the readme a few minutes ago, so the command to run bblfsh server is:

```
BBLFSH_DRIVER_IMAGES="python=docker://bblfsh/python-driver:v0.8.2;java=docker://bblfsh/java-driver:v0.6.0" docker run -e BBLFSH_DRIVER_IMAGES -d --privileged -p 9432:9432 --name bblfsh bblfsh/server:v0.7.0 --log-level DEBUG
```

Seems a bit complicated but it just sets the previous versions since we had a major update today.

Regarding `Cannot connect to the Docker daemon. Is the docker daemon running on this host?`, your user needs to belong to `docker` group. See [here](https://docs.docker.com/engine/installation/linux/linux-postinstall/#manage-docker-as-a-non-root-user)

**Comment by asah** [comment]
thx!  since most users login via a non-root acount, I recommend adding the
docker group instructions.  On ubuntu 16.04, the command is "sudo usermod
-a docker $USER; sudo su - $USER" ("su -" is needed to reload the groups
list)

the BBLFSH_DRIVER_IMAGES=... command worked great!

On Tue, Sep 19, 2017 at 12:02 PM, Vadim Markovtsev <notifications@github.com

**Comment by asah** [comment]
oh, and the final command (docker run -it --rm srcd/ast2vec --help) worked as well.

**Comment by eiso** [comment]
@asah Hey Adam, great to see you here and thanks for creating an issue. Be sure to also join our Slack for real-time feedback @ http://sourced.tech/

**Comment by vmarkovtsev** [comment]
Fixed by https://github.com/src-d/ast2vec/commit/4ca466006976afee366ec69f14273ccd87f93369
